### ISSUE TITLE
can't run the example demo

### ISSUE THREAD

**Issue by BabysbreathJJ** [vyorkin-personal/erlyeditor#2]
Hi , I clone the code and try to run the example.
I have made my node version 5.10.0 and run "npm install", but when I run "npm start" 
![image](https://cloud.githubusercontent.com/assets/6993633/21742209/a99c1720-d524-11e6-9013-dd6b5adc79e3.png)

I think it error because lack of the .babelrc file, so I add the .babelrc under the example folder.
Then I try to run "npm start " again , it still has error and I don't know how to fix it, pls help me . Thx! 
The error shows below:
![image](https://cloud.githubusercontent.com/assets/6993633/21742224/154df5b0-d525-11e6-8fb9-49ff069d3d7a.png)

**Comment by vyorkin** [comment]
Hey @BabysbreathJJ ! Thank you for reporting issue, this project was just a test assignment I've done a long time ago. Many things are done wrong there and I'm not sure its a good example to learn from.

**Comment by vyorkin** [comment]
I guess it won't be easy to setup it up now, but you can try the following steps (as described in README):

- `cp .example.env .env` and set required environment variables
- run `npm install`
- install peer dependencies by running `npm install react react-dom react-motion`
- you have to npm install and build (npm run build:lib) modules that is pulled from github by yourself

and I don't even remembers what the last step actually means (%

**Comment by vyorkin** [comment]
closing, since this project is a joke
